src/client/app/routes/run.js, src/common/dataDb.js, src/validator/validator.js
=> Fixed runs with no ruleset not showing up in UI

build/bin/build.sh, build/bin/tagImages.sh, package.json, src/client/app/styles/app.css, src/client/app/templates/application.hbs, src/client/app/templates/index.hbs, src/client/package.json, src/server/server.js
added better versioning, show version in UI, script to help with tagging containers
=> Build improvements

src/runtime/rulesets/CheckDataRulesetConfig.json, test_config/rulesets/CheckDataRulesetConfig.json
=> Switched no numbers allowed regex

src/client/app/controllers/index.js, src/client/app/routes/edit-ruleset.js, src/client/app/templates/index.hbs, src/common/dataDb.js
=> Fixed not being able to link to runs with deleted rulesets

database/dbloader/migrations/1508256268530_0.2.3.js
=> switched json columns to jsonb type

src/client/app/controllers/index.js
=> Reset page counter when filter changes

src/common/dataDb.js
=> Fixed saving and cloning new rulesets

deploy/initPluto.sh, src/start_dev_db.sh, startPluto.sh
=> Used validator config to set db connection properties in startup scripts #86

src/rules/CheckColumnRegEx.js, src/validator/tests/unit/test-CheckColumnRegEx.js
=> Added option to choose warning or error on regex failure

src/api/ParserRuleAPI.js, src/api/RuleAPI.js, src/api/TableParserAPI.js, src/api/TableRuleAPI.js, src/rules/AddRegExColumn.js, src/rules/AddRowIdColumn.js, src/rules/CSVParser.js, src/rules/CheckColumnCount.js, src/rules/CheckColumnRegEx.js, src/rules/CheckColumnType.js, src/rules/CheckLatLong.js, src/rules/DeleteInternalColumn.js, src/rules/RunPythonScript.js, src/validator/tests/MemoryWriterStream.js, src/validator/tests/dbProxy.js, src/validator/tests/testDataCSVFile2.csv, src/validator/tests/testRules/RuleCountRows.js, src/validator/tests/testRules/RuleErrorFromColumn.js, src/validator/tests/testRules/manifest.json, src/validator/tests/unit/test-AddRegexColumn.js, src/validator/tests/unit/test-CheckColumnRegEx.js, src/validator/tests/unit/test-CheckColumnType.js, src/validator/tests/unit/test-CheckLatLong.js, src/validator/tests/unit/test-DeleteColumn.js, src/validator/tests/unit/test-validator-errorhandling.js, src/validator/tests/unit/test-validator.js, src/validator/validator.js
=> Bugfix/error row numbers off #128

package.json, src/api/ParserRuleAPI.js, src/api/TableRuleAPI.js, src/api/errorHandlerAPI.js, src/rules/AddRegExColumn.js, src/rules/CSVParser.js, src/rules/CheckColumnCount.js, src/rules/CheckColumnRegEx.js, src/rules/CheckColumnType.js, src/rules/CheckLatLong.js, src/rules/internal/AddRestAPIColumnBase.js, src/rules/internal/AddRowIdColumn.js, src/rules/internal/DeleteInternalColumn.js, src/validator/ErrorLogger.js, src/validator/tests/testRules/RuleErrorFromColumn.js, src/validator/tests/testRules/RulePassFail.js, src/validator/tests/unit/test-AddRegexColumn.js, src/validator/tests/unit/test-AddRestAPIColumnBase.js, src/validator/tests/unit/test-CheckColumnCount.js, src/validator/tests/unit/test-config.js, src/validator/tests/unit/test-validator-errorhandling.js, src/validator/tests/unit/test-validator.js
Added the csvparser and base class support to make metered REST api calls and put the results in a new class.  Addresses #89
=> Base rest api rule support (#89)

database/dbloader/migrations/1507315768211_0.2.2.js, database/dbloader/migrations/1509463229643_0.2.5.js, src/client/app/controllers/edit-ruleset.js, src/client/app/helpers/show-rule-editor.js, src/client/app/models/ruleset.js, src/client/app/models/run.js, src/client/app/styles/app.css, src/client/app/templates/application.hbs, src/client/app/templates/edit-ruleset.hbs, src/client/app/templates/edit-ruleset/run.hbs, src/common/dataDb.js, src/server/router.js, src/server/routes/rulesets.js, src/validator/RuleSet.js, src/validator/tests/unit/test-AddRestAPIColumnBase.js, src/validator/tests/unit/test-dataDb.js
=> Feature/user permissions #131 #76

src/client/app/controllers/index.js, src/common/dataDb.js, src/server/routes/rulesets.js, src/server/server.js
Addresses:
#140 
#93 
#103 
#92 
#99 
#53 
#94
=> Main page UI cleanup & fixes

.gitattributes, dev_nginx.conf, package.json, src/client/app/adapters/application.js, src/client/app/controllers/application.js, src/client/app/controllers/index.js, src/client/app/models/run.js, src/client/app/models/user.js, src/client/app/routes/index.js, src/client/app/templates/index.hbs, src/client/tests/unit/adapters/application-test.js, src/client/tests/unit/controllers/application-test.js, src/client/tests/unit/models/user-test.js, src/common/dataDb.js, src/server/router.js, src/server/routes/rulesets.js, src/server/routes/runs.js, src/server/routes/user.js, startPluto.sh, test_nginx.conf
=> Feature/filter by group #144

src/client/app/routes/index.js, src/client/app/routes/rulesets.js, src/client/app/templates/components/add-ruleset.hbs, src/client/app/templates/index.hbs, src/client/app/templates/rulesets.hbs
=> Added default lists of sources and targets on the add-ruleset pop-up for #178

src/client/app/controllers/rulesets.js, src/client/app/templates/rulesets.hbs
For #189 
Also cleaned up the file a bit to remove Ember compile errors
=> Added source, target and parser when cloning a ruleset

src/api/TableParserAPI.js, src/api/errorHandlerAPI.js, src/rules/CSVParser.js, src/rules/CheckColumnNames.js, src/rules/manifest.json, src/validator/tests/unit/test-CheckColumnNames.js
Lso added ability for column name order to be independent of the specified names
#177
=> added rule to test for column names

src/client/app/components/add-ruleset.js, src/client/app/controllers/edit-ruleset.js, src/client/app/controllers/rulesets.js, src/client/app/controllers/runs.js, src/client/app/models/run.js, src/client/app/models/user.js, src/client/app/routes/index.js, src/client/app/routes/rulesets.js, src/client/app/routes/runs.js, src/client/app/templates/edit-configured-rule.hbs, src/client/app/templates/edit-ruleset.hbs, src/client/app/templates/index.hbs, src/client/app/templates/rulesets.hbs, src/client/app/templates/runs.hbs, src/common/dataDb.js, src/server/router.js, src/server/routes/processFile.js, src/server/routes/rulesets.js, src/server/routes/runs.js, src/server/routes/user.js
Addresses #198, #194, #190, and fixes #209
=> Rename ruleset and references to the ruleset_id/filename

src/client/app/controllers/run.js, src/client/app/routes/application.js, src/client/app/routes/edit-ruleset.js, src/client/app/routes/rulesets.js, src/client/app/templates/index.hbs, src/client/app/templates/rulesets.hbs, src/client/app/templates/run.hbs, src/client/tests/unit/routes/application-test.js
=> Fixed defaults for logged in user

src/client/app/controllers/rulesets.js, src/client/app/controllers/runs.js, src/client/app/templates/index.hbs, src/client/app/templates/rulesets.hbs
Also fixed group filter when no user is loaded
=> Increased default list size to 20

src/client/app/templates/admin/configuredrule.hbs, src/client/app/templates/components/add-ruleset.hbs
Updated buttons on uploads/downloads config
won't close create pop-ups if clicking outside
=> Minor UI fixes

src/client/app/styles/app.css, src/client/app/templates/application.hbs
Separates footer from the rest of the view. I put a background on it because seeing text disappear underneath white is strange.
=> separate scroll bar

src/server/routes/processFile.js, src/server/server.js, src/validator/RuleSet.js, src/validator/startValidator.js, src/validator/validator.js, stack/filebeat/filebeat.yml
=> Cleaned up server output to be json

CHANGELOG.md, docs/validatorConfig.md, src/common/Util.js, src/server/server.js, src/validator/startValidator.js, src/validator/tests/unit/test-Util.js
=> Feature/confing env support #436

database/dbloader/configureDatabase.js, database/dbloader/run_importer_in_docker.sh
=> Fixed database loader container for the dev docker-compose

src/client/app/templates/edit-basic-ruleset.hbs, src/client/app/templates/edit-ruleset.hbs
Added a text message explaining to the user why the Save button is disabled.
=> Issue #519

docs/release.md
=> Document release procedures

CHANGELOG.md, package-lock.json, package.json, src/client/package-lock.json, src/client/package.json
Final commit of release steps per https://github.com/unchartedsoftware/PLUTO/blob/develop/docs/release.md
=> Update to version 1.0.16

CHANGELOG.md, docs/validatorConfig.md, src/client/app/components/add-configured-rule.js, src/client/app/routes/admin/configuredrule.js, src/client/app/templates/admin/configuredrule.hbs, src/client/app/templates/components/add-configured-rule.hbs, src/common/dataDb.js, src/server/routes/configuredRules.js, src/server/routes/exportConfig.js
=> Fixes addAuth population of AUTH-GROUP on export

CHANGELOG.md, package-lock.json, package.json, src/client/package-lock.json, src/client/package.json
Updates to version 1.0.17 for next set of releases.
=> Update 1.0.17 versions
